config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users,:controllers => { registrations: 'users/registrations',sessions: 'users/sessions' }

  resources :user_steps
  resources :users, only: [:new, :create]
  resources :pages
  resources :subscriptions do
    get 'cancel'
  end
  root 'pages#index'
  resources :profiles, only: [:index]
  resources :school_closing_steps
  resources :football_steps
  resources :tap_programs
  resources :after_school_registrations

  get "qc_before_after_school" => "pages#qc_before_after_school"
  get "qc_after_school" => "pages#qc_after_school"
  get "qc_befor_school" => "pages#qc_befor_school"
  get "taps_after_school" => "pages#taps_after_school"
  get "taps_gallery" => "pages#taps_gallery"
  get "payment" => "after_school_registrations#payment"
  get '/st_payment' => 'pages#st_payment'
  get 'payment' => 'school_closing_steps#payment'
  get 'football_payment' => 'football_steps#football_payment'
  get 'download_pdf' => 'profiles#download_pdf'
  get 'about' => 'pages#about'
  get 'contact' => 'pages#contact'
  get 'program' => 'pages#program'
  get 'gallery' => 'pages#gallery'
  get 'football_camp' => 'tap_programs#football_camp'
  post 'register_football' => 'tap_programs#register_football'

  post 'school_registration/:id' => 'pages#school_registration', as: :school_registration

  post '/check_coupon_code', to: 'subscriptions#check_coupon_code'

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
	 layout 'application'
	require 'prawn'
	def index
		
	end

	def download_pdf
		report_data = PdfReports.new(current_user).pdf_page_content
		file_name = "#{current_user.created_at.strftime('%m/%d/%Y')}.pdf"
		send_data( report_data, :type => "application/pdf", :style => 'inline', :filename => file_name) 
	end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/index.html.erb
<div class="container" style="margin-top: 100px; margin-bottom: 50px;">
<div id="content">
<div class="container">
  <div class="row">
    <div class="col-md-7 col-md-offset">
      <h2>Profile</h2>
      <div class="pull-left">
        First Name : <%= current_user.first_name.titleize  if current_user.first_name.present?%>
        <br>
        Last Name : <%= current_user.last_name.titleize if current_user.last_name.present?%>
        <br>
        Email : <%= current_user.email.capitalize if current_user.email.present?%>
        <br>
        Gender : <%= current_user.gender%>
        <br>
        Age : <%= current_user.age%>
      </div>
      <div class="pull-right">
        School Name : <%= current_user.school_name.titleize if current_user.school_name.present?%>
        <br>
        Grade Year : <%= current_user.grade_year%>
        <br>
        Father Name : <%= current_user.father_name%>
        <br>
        Mother Name : <%= current_user.mother_name%>
      </div>
    </div>
  </div>
  <br>
  <div class="portlet box red">
    <div class="portlet-title">
      <div class="caption">
        <i class="fa fa-cogs"></i>Subscriptions
      </div>
    </div>
    <div class="portlet-body">
      <div class="table-scrollable">
        <table class="table table-hover">
          <thead>
            <tr>
              <th> Plan Interval </th>
              <th> Plan Name </th>
              <th> Status</th>
              <th> Cancel </th>
            </tr>
          </thead>
          <tbody>
            <% current_user.subscriptions.each do |subscription| %>
              <tr>
                <td> <%= current_user.plan.titleize%> </td>
                <td>
                  <% if subscription.plan_name.nil? %> 
                    No Plan 
                  <% else %>
                    <%= subscription.plan_name.titleize%>
                  <% end %>
                </td>
                <td> <%= subscription.try(:active)%> </td>
                <td>
                  <% if subscription.active %>
                    <%= link_to "Cancel", subscription_cancel_path(subscription.stripe_card_token), class: "btn btn-success btn-sm" %>
                  <% else %>
                    <%= link_to "Subscription Cancelled", subscription_cancel_path(subscription.stripe_card_token), class: "btn btn-success btn-sm", disabled: true %>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <%= form_tag download_pdf_path,method: :get do %>
    <% if current_user.stripe_customers.present? %>
      <%= submit_tag 'Download Pdf', class: "btn btn-success btn-lg" %>
    <%else%>
      <%= submit_tag 'Submit', class: "btn btn-default btn-lg disabled" %>
    <%end%>
  <%end%>
</div>
 <div class="wave2"></div>
</div>
</div>