config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users,:controllers => { registrations: 'users/registrations',sessions: 'users/sessions' }

  resources :user_steps
  resources :users, only: [:new, :create]
  resources :pages
  resources :subscriptions do
    get 'cancel'
  end
  root 'pages#index'
  resources :profiles, only: [:index]
  resources :school_closing_steps
  resources :football_steps
  resources :tap_programs
  resources :after_school_registrations

  get "qc_before_after_school" => "pages#qc_before_after_school"
  get "qc_after_school" => "pages#qc_after_school"
  get "qc_befor_school" => "pages#qc_befor_school"
  get "taps_after_school" => "pages#taps_after_school"
  get "taps_gallery" => "pages#taps_gallery"
  get "payment" => "after_school_registrations#payment"
  get '/st_payment' => 'pages#st_payment'
  get 'payment' => 'school_closing_steps#payment'
  get 'football_payment' => 'football_steps#football_payment'
  get 'download_pdf' => 'profiles#download_pdf'
  get 'about' => 'pages#about'
  get 'contact' => 'pages#contact'
  get 'program' => 'pages#program'
  get 'gallery' => 'pages#gallery'
  get 'football_camp' => 'tap_programs#football_camp'
  post 'register_football' => 'tap_programs#register_football'

  post 'school_registration/:id' => 'pages#school_registration', as: :school_registration

  post '/check_coupon_code', to: 'subscriptions#check_coupon_code'

end

app/views/pages/_form.html.erb
<section id="wizard">
  <%= simple_form_for @user, url: school_registration_path(@user),method: :post, class: "form-horizontal",novalidate: "novalidate" do |f| %>
		<div id="rootwizard">
			<ul class="nav nav-pills">
			  <li class="active"><a href="#tab1" data-toggle="tab" aria-expanded="true">First</a></li>
				<li><a href="#tab2" data-toggle="tab">Second</a></li>
				<li><a href="#tab3" data-toggle="tab">Third</a></li>
			</ul>
		  <div id="bar" class="progress">
        <div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%;"></div>
      </div>
			<div class="tab-content">
			  <div class="tab-pane active" id="tab1">

          <%= f.input :first_name, placeholder: 'user@domain.com',class: "required email" %>
          <%= f.input :last_name, placeholder: 'user@domain.com',class: "required email" %>
          <%= f.input :gender, as: :check_boxes %>
          <%= f.input :age %>
          <%= f.input :school_name %>
          <%= f.input :grade_year %>
          <%= f.input :address %>
          <%= f.input :city %>
          <%= f.input :state %>
          <%= f.input :zip_code %>
        </div>
		    <div class="tab-pane" id="tab2">
		      <div class="control-group">
				    <label class="control-label" for="url">URL</label>
				    <div class="controls">
				      <input type="text" id="urlfield" name="urlfield" class="required url">
				    </div>
				  </div>
		    </div>
				<div class="tab-pane" id="tab3">
					3
			  </div>
				<ul class="pager wizard">
					<li class="previous first disabled" style="display:none;"><a href="#">First</a></li>
					<li class="previous disabled"><a href="javascript:void(0)">Previous</a></li>
					<li class="next last" style="display:none;"><a href="#">Last</a></li>
					<%=f.submit 'Next',class: "next"%>
				  <li class="next"><a href="javascript:void(0)">Next</a></li>
				</ul>
			</div>
		</div>
	<%end%>
</section>

app/views/pages/about.html.erb
<div class="container" style="
    margin-top: 100px; margin-bottom: 50px;">
  <div class="row">
<div id="content">
  <div class="breadcrumbs1_wrapper">
    <div class="container">
      <div class="breadcrumbs1"><%=link_to 'Home',pages_path%><span></span>About Us</div>
    </div>
  </div>

  <div class="container">
    <div class="row">
      <div class="col-sm-8">

        <h2>who we are</h2>

        <div class="thumb2">
          <div class="thumbnail clearfix">
            <figure class="img-circle">
              <img src="/assets/about01.jpg" alt="" class="img-responsive">
            </figure>
            <div class="caption">
              <p>
                <strong class="text-uppercase">
                  We are preparing youth for education, self-suffiency, corporate america and tomorrow's challenges while developing athletic talents..
                </strong>
              </p>
              <p>
                At T.A.P.S, we believe learning should mean fun. Our programs are designed for children of various grades. We believe that our enrichment programs is an excellent way to improve children's academic performance and social skills.
              </p>
              <!-- <a href="#" class="btn-default btn1">donate</a> -->
            </div>
          </div>
        </div>



      </div>
      <div class="col-sm-4">

        <h2 class="c">Why Choose US</h2>

        <ul class="ul1">
          <li class="clearfix"><i class="fa fa-thumbs-o-up"></i><span>Enrichment.</span></li>
          <li class="clearfix"><i class="fa fa-trophy"></i><span>Certified Teachers.</span></li>
          <li class="clearfix"><i class="fa fa-smile-o"></i><span>Academic Club.</span></li>
          <li class="clearfix"><i class="fa fa-rocket"></i><span>Home Economics.</span></li>
          <li class="clearfix"><i class="fa fa-bell"></i><span> before and after-school .</span></li>
          <li class="clearfix"><i class="fa fa-cutlery"></i><span>cultural activities.</span></li>
          <li class="clearfix"><i class="fa fa-eye"></i><span>Athletic Club.</span></li>
          <li class="clearfix"><i class="fa fa-heart"></i><span>Arts Club.</span></li>
        </ul>





      </div>
    </div>

    <h2>our team</h2>

    <div class="row">
      <div class="col-sm-3">
        <div class="thumb3">
          <div class="thumbnail clearfix">
            <a href="#">
              <figure class="">
                <img src="/assets/about02.jpg" alt="" class="img-responsive">
              </figure>
              <div class="caption">
                <div class="txt1">Jermaine Smith</div>
                <div class="txt2">Founder</div>
              </div>
            </a>
          </div>
        </div>
      </div>
      <div class="col-sm-3">
        <div class="thumb3">
          <div class="thumbnail clearfix">
            <a href="#">
              <figure class="">
                <img src="/assets/about03.jpg" alt="" class="img-responsive">
              </figure>
              <div class="caption">
                <div class="txt1">Cynthia Smith</div>
                <div class="txt2">Administrator</div>
              </div>
            </a>
          </div>
        </div>
      </div>
      <div class="col-sm-3">
        <div class="thumb3">
          <div class="thumbnail clearfix">
            <a href="#">
              <figure class="">
                <img src="/assets/about04.jpg" alt="" class="img-responsive">
              </figure>
              <div class="caption">
                <div class="txt1">Staff</div>
                <div class="txt2">teacher</div>
              </div>
            </a>
          </div>
        </div>
      </div>
      <div class="col-sm-3">
        <div class="thumb3">
          <div class="thumbnail clearfix">
            <a href="#">
              <figure class="">
                <img src="/assets/about05.jpg" alt="" class="img-responsive">
              </figure>
              <div class="caption">
                <div class="txt1">staff</div>
                <div class="txt2">teacher</div>
              </div>
            </a>
          </div>
        </div>
      </div>
    </div>





  </div>
  <div class="wave2"></div>
</div>
</div>
</div>

app/views/pages/contact.html.erb
<div class="container" style="
    margin-top: 100px; margin-bottom: 50px;">
  <div class="row">
<div id="content">
  <div class="breadcrumbs1_wrapper">
    <div class="container">
      <div class="breadcrumbs1"><%=link_to 'Home',pages_path%><span></span></div>
    </div>
  </div>

  <div class="container">

    <div class="row">
      <div class="col-sm-3">

        <h2>contact Us</h2>

        <div class="thumb4">
          <div class="thumbnail clearfix">
            <figure class="img-polaroid">
              <img src="/assets/contacts01.jpg" alt="" class="img-responsive">
            </figure>
            <div class="caption">
              <p>
                9100 Olmsted Dr,<br>
Charlotte, NC.<br>
Telephone: 704-749-0528<br>
E-mail: <a href="#">tapssportsacademy@gmail.com</a>
              </p>
            </div>
          </div>
        </div>




      </div>
      <div class="col-sm-9">

        <h2 class="c">Contact Form</h2>

        <div id="note"></div>
        <div id="fields">
          <form id="ajax-contact-form" class="form-horizontal" action="javascript:alert('success!');">
            <div class="row">
              <div class="col-sm-4">
                <div class="form-group">
                    <label for="inputName">Your Name</label>
                    <input type="text" class="form-control" id="inputName" name="name" value="Full Name" onBlur="if(this.value=='') this.value='Full Name'" onFocus="if(this.value =='Full Name' ) this.value=''">
                </div>
              </div>
              <div class="col-sm-4">
                <div class="form-group">
                    <label for="inputEmail">Email</label>
                    <input type="text" class="form-control" id="inputEmail" name="email" value="E-mail address" onBlur="if(this.value=='') this.value='E-mail address'" onFocus="if(this.value =='E-mail address' ) this.value=''">
                </div>
              </div>
              <div class="col-sm-4">
                <div class="form-group">
                    <label for="inputPhone">Phone</label>
                    <input type="text" class="form-control" id="inputPhone" name="phone" value="Phone" onBlur="if(this.value=='') this.value='Phone'" onFocus="if(this.value =='Phone' ) this.value=''">
                </div>
              </div>

            </div>

            <div class="row">
              <div class="col-sm-12">
                <div class="form-group">
                    <label for="inputMessage">Your Message</label>
                    <textarea class="form-control" rows="5" id="inputMessage" name="content" onBlur="if(this.value=='') this.value='Message'"
                                onFocus="if(this.value =='Message' ) this.value=''">Message</textarea>
                </div>
              </div>
            </div>
            
            <button type="submit" class="btn-default btn-cf-submit">Submit</button>
          </form>
        </div>




      </div>
    </div>

    <h2 class="c">map</h2>

    <figure class="google_map">
      <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d13023.086444686476!2d-80.746715!3d35.311656!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x88541c3cfc836d17%3A0xbdf42fd6f88a83ba!2s9100+Olmsted+Dr%2C+Charlotte%2C+NC+28262!5e0!3m2!1sen!2sus!4v1457247619016" width="800" height="600" frameborder="0" style="border:0" allowfullscreen></iframe>
    </figure>




  </div>
  <div class="wave2"></div>
</div>
</div>
</div>

app/views/pages/gallery.html.erb
<script>
$(document).ready(function() {
  //

  // touchTouch
  $('.thumb-isotope .thumbnail a').touchTouch();



}); //
$(window).load(function() {
  //

  /*----------------------------------------------------*/
  // ISOTOPE BEGIN
  /*----------------------------------------------------*/
  var $container = $('#container');
  //Run to initialise column sizes
  updateSize();

  //Load fitRows when images all loaded
  $container.imagesLoaded( function(){

      $container.isotope({
          // options
          itemSelector : '.element',
          layoutMode : 'fitRows',
          transformsEnabled: true,
          columnWidth: function( containerWidth ) {
              containerWidth = $browserWidth;
              return Math.floor(containerWidth / $cols);
            }
      });
  });

  // update columnWidth on window resize
  $(window).smartresize(function(){
      updateSize();
      $container.isotope( 'reLayout' );
  });

  //Set item size
  function updateSize() {
      $browserWidth = $container.width();
      $cols = 4;

      if ($browserWidth >= 1170) {
          $cols = 4;
      }
      else if ($browserWidth >= 767 && $browserWidth < 1170) {
          $cols = 3;
      }
      else if ($browserWidth >= 480 && $browserWidth < 767) {
          $cols = 2;
      }
      else if ($browserWidth >= 0 && $browserWidth < 480) {
          $cols = 1;
      }
      //console.log("Browser width is:" + $browserWidth);
      //console.log("Cols is:" + $cols);

      // $gutterTotal = $cols * 20;
      $browserWidth = $browserWidth; // - $gutterTotal;
      $itemWidth = $browserWidth / $cols;
      $itemWidth = Math.floor($itemWidth);

      $(".element").each(function(index){
          $(this).css({"width":$itemWidth+"px"});
      });



    var $optionSets = $('#options .option-set'),
        $optionLinks = $optionSets.find('a');

    $optionLinks.click(function(){
      var $this = $(this);
      // don't proceed if already selected
      if ( $this.hasClass('selected') ) {
        return false;
      }
      var $optionSet = $this.parents('.option-set');
      $optionSet.find('.selected').removeClass('selected');
      $this.addClass('selected');

      // make option object dynamically, i.e. { filter: '.my-filter-class' }
      var options = {},
          key = $optionSet.attr('data-option-key'),
          value = $this.attr('data-option-value');
      // parse 'false' as false boolean
      value = value === 'false' ? false : value;
      options[ key ] = value;
      if ( key === 'layoutMode' && typeof changeLayoutMode === 'function' ) {
        // changes in layout modes need extra logic
        changeLayoutMode( $this, options )
      } else {
        // otherwise, apply new options
        $container.isotope( options );
      }

      return false;
    });

  };
  /*----------------------------------------------------*/
  // ISOTOPE END
  /*----------------------------------------------------*/



}); //
</script>

<div id="content">
  <div class="breadcrumbs1_wrapper">
    <div class="container">
      <div class="breadcrumbs1"><%=link_to 'Home', pages_path %><span></span>Gallery</div>
    </div>
  </div>

  <div class="container">

    <h2 class="c">Photo Gallery</h2>

    <div id="options" class="clearfix">
      <ul id="filters" class="pagination option-set clearfix" data-option-key="filter">
        <li><a href="#filter" data-option-value="*" class="selected">Show All</a></li>
        <li><a href="#filter" data-option-value=".isotope-filter1">Category 1</a></li>
        <li><a href="#filter" data-option-value=".isotope-filter2">Category 2</a></li>
        <li><a href="#filter" data-option-value=".isotope-filter3">Category 3</a></li>
      </ul>
    </div>

    <div class="isotope-box">
                  <div id="container" class="clearfix">
                    <ul class="thumbnails" id="isotope-items">
                      <li class="element isotope-filter1">
                        <div class="thumb-isotope">
                          <div class="thumbnail clearfix">
              
                              <figure>
                                <img src="/assets/gallery01.jpg" alt=""><em></em>
                              </figure>
                              
                            </a>
                          </div>
                        </div>
                      </li>
                      <li class="element isotope-filter2">
                        <div class="thumb-isotope">
                          <div class="thumbnail clearfix">
                            
                              <figure>
                                <img src="/assets/gallery02.jpg" alt=""><em></em>
                              </figure>
                              
                            </a>
                          </div>
                        </div>
                      </li>
                      <li class="element isotope-filter3">
                        <div class="thumb-isotope">
                          <div class="thumbnail clearfix">
                            
                              <figure>
                                <img src="/assets/gallery03.jpg" alt=""><em></em>
                              </figure>
                              
                            </a>
                          </div>
                        </div>
                      </li>
                      <li class="element isotope-filter1">
                        <div class="thumb-isotope">
                          <div class="thumbnail clearfix">
                            
                              <figure>
                                <img src="/assets/gallery04.jpg" alt=""><em></em>
                              </figure>
                             
                            </a>
                          </div>
                        </div>
                      </li>
                      <li class="element isotope-filter2">
                        <div class="thumb-isotope">
                          <div class="thumbnail clearfix">
                            
                              <figure>
                                <img src="/assets/gallery05.jpg" alt=""><em></em>
                              </figure>
                              
                            </a>
                          </div>
                        </div>
                      </li>
                      <li class="element isotope-filter3">
                        <div class="thumb-isotope">
                          <div class="thumbnail clearfix">
                            
                              <figure>
                                <img src="/assets/gallery06.jpg" alt=""><em></em>
                              </figure>
                              
                            </a>
                          </div>
                        </div>
                      </li>
                      <li class="element isotope-filter1">
                        <div class="thumb-isotope">
                          <div class="thumbnail clearfix">
                            
                              <figure>
                                <img src="/assets/gallery07.jpg" alt=""><em></em>
                              </figure>
                              
                            </a>
                          </div>
                        </div>
                      </li>
                      <li class="element isotope-filter2">
                        <div class="thumb-isotope">
                          <div class="thumbnail clearfix">
                           
                              <figure>
                                <img src="/assets/gallery08.jpg" alt=""><em></em>
                              </figure>
                              
                            </a>
                          </div>
                        </div>
                      </li>
                      <li class="element isotope-filter3">
                        <div class="thumb-isotope">
                          <div class="thumbnail clearfix">
                            
                              <figure>
                                <img src="/assets/gallery09.jpg" alt=""><em></em>
                              </figure>
                              
                            </a>
                          </div>
                        </div>
                      </li>
                      <li class="element isotope-filter1">
                        <div class="thumb-isotope">
                          <div class="thumbnail clearfix">
                            
                              <figure>
                                <img src="/assets/gallery10.jpg" alt=""><em></em>
                              </figure>
                              
                            </a>
                          </div>
                        </div>
                      </li>
                      <li class="element isotope-filter2">
                        <div class="thumb-isotope">
                          <div class="thumbnail clearfix">
                            
                              <figure>
                                <img src="/assets/gallery11.jpg" alt=""><em></em>
                              </figure>
                              
                            </a>
                          </div>
                        </div>
                      </li>
                      <li class="element isotope-filter3">
                        <div class="thumb-isotope">
                          <div class="thumbnail clearfix">
                            
                              <figure>
                                <img src="/assets/gallery12.jpg" alt=""><em></em>
                              </figure>
                              
                            </a>
                          </div>
                        </div>
                      </li>
                    </ul>
                  </div>
                </div>









  </div>
  <div class="wave2"></div>
</div>

app/views/pages/program.html.erb
<div id="content">
  <div class="breadcrumbs1_wrapper">
    <div class="container">
      <div class="breadcrumbs1"><a href="index.html">Home</a><span></span>Services</div>
    </div>
  </div>

  <div class="container">
    <div class="row">
      <div class="col-sm-8">

        <h2>About our services</h2>

       

        <div class="thumb2">
          <div class="thumbnail clearfix">
            <figure class="img-polaroid">
              <img src="/assets/services02.jpg" alt="" class="img-responsive">
            </figure>
            <div class="caption">
              <p>
                <strong class="text-uppercase">
                  T.A.P.S (Teaching Athletes Plans for Success) Inc. is a 501(c)(3) non-profit organization 
                </strong>
              </p>
              <p>
                T.A.P.S. exists to organize, primarily through the vehicle of athletics and youth development, a positive, enriching environment contributing to an improved quality of life for our area youth and families.
              </p>
              <%=link_to 'read more', tap_programs_path(query: "taps_afterschool"), class: "btn-default btn1"%>
            </div>
          </div>
        </div>

        <div class="thumb2">
          <div class="thumbnail clearfix">
            <figure class="img-polaroid">
              <img src="/assets/services03.jpg" alt="" class="img-responsive">
            </figure>
            <div class="caption">
              <p>
                <strong class="text-uppercase">
                  School may be out, but education and adventure are always in at T.A.P.S Summer Enrichment Camp! With activities for kindergarten – rising grade 8
                </strong>
              </p>
              <p>
                there are tons of programs to get kids excited about Academics, Arts and
               Athletics. The club, studio and lab environment encourages experimentation, exploration and discovery geared for 
               specific age groups.
              </p>
              <%=link_to 'read more', tap_programs_path(query: "summer_camp"), class: "btn-default btn1"%>
            </div>
          </div>
        </div>

        <div class="thumb2">
          <div class="thumbnail clearfix">
            <figure class="img-polaroid">
              <img src="/assets/services04.jpg" alt="" class="img-responsive">
            </figure>
            <div class="caption">
              <p>
                <strong class="text-uppercase">
                  Golden Norsemen Athletics
                </strong>
              </p>
              <p>
                Golden Norsemen Athletics offers Football, Basketball, Baseball and Cheer to youth ages 5 - 14.  We participate in AAU  that offers over 30 different sports to youth.
              </p>
              <%=link_to 'read more', tap_programs_path(query: "noresman_football"), class: "btn-default btn1"%>
            </div>
          </div>
        </div>



      </div>
      <div class="col-sm-4">

        <h2 class="c">Academics</h2>

        <div class="thumb4">
          <div class="thumbnail clearfix">
            <figure class="img-polaroid">
              <img src="/assets/services05.jpg" alt="" class="img-responsive">
            </figure>
            <div class="caption">
              <p>
                <strong class="text-uppercase">
                </strong>
              </p>
              <p>
                Our Academic program serves to empower the mind as well as address issues the youth face. We have a staff of certified teachers to ensure we remain relevant with what the youth need to succeed in the class. Within our Academic wing we have STEM which consist of Science, Technology, Math and Engineering labs , and Literacy class. We also embrace non traditional such as Home Economics, Public Speaking, and Entrepreneurship and Philanthropy. We also provide tutoring and academic mentoring.
              </p>
            </div>
          </div>
        </div>

        <h2 class="c">Services list</h2>

        <ul class="ul1">
          <li class="clearfix"><i class="fa fa-thumbs-o-up"></i><span>Enrichment.</span></li>
          <li class="clearfix"><i class="fa fa-trophy"></i><span>Certified Teachers.</span></li>
          <li class="clearfix"><i class="fa fa-smile-o"></i><span>Academic Club.</span></li>
          <li class="clearfix"><i class="fa fa-rocket"></i><span>Home Economics.</span></li>
          <li class="clearfix"><i class="fa fa-bell"></i><span> before and after-school .</span></li>
          <li class="clearfix"><i class="fa fa-cutlery"></i><span>cultural activities.</span></li>
          <li class="clearfix"><i class="fa fa-eye"></i><span>Athletic Club.</span></li>
          <li class="clearfix"><i class="fa fa-heart"></i><span>Arts Club.</span></li>
        </ul>





      </div>
    </div>




  </div>
  <div class="wave2"></div>
</div>