config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users,:controllers => { registrations: 'users/registrations',sessions: 'users/sessions' }

  resources :user_steps
  resources :users, only: [:new, :create]
  resources :pages
  resources :subscriptions do
    get 'cancel'
  end
  root 'pages#index'
  resources :profiles, only: [:index]
  resources :school_closing_steps
  resources :football_steps
  resources :tap_programs
  resources :after_school_registrations

  get "qc_before_after_school" => "pages#qc_before_after_school"
  get "qc_after_school" => "pages#qc_after_school"
  get "qc_befor_school" => "pages#qc_befor_school"
  get "taps_after_school" => "pages#taps_after_school"
  get "taps_gallery" => "pages#taps_gallery"
  get "payment" => "after_school_registrations#payment"
  get '/st_payment' => 'pages#st_payment'
  get 'payment' => 'school_closing_steps#payment'
  get 'football_payment' => 'football_steps#football_payment'
  get 'download_pdf' => 'profiles#download_pdf'
  get 'about' => 'pages#about'
  get 'contact' => 'pages#contact'
  get 'program' => 'pages#program'
  get 'gallery' => 'pages#gallery'
  get 'football_camp' => 'tap_programs#football_camp'
  post 'register_football' => 'tap_programs#register_football'

  post 'school_registration/:id' => 'pages#school_registration', as: :school_registration

  post '/check_coupon_code', to: 'subscriptions#check_coupon_code'

end

app/views/layouts/_footer_content.html.erb
<div class="bot1_wrapper">

  <div class="container">

    <div class="logo2_wrapper">
      <a href="index.html" class="logo2">
        <img src="/assets/logo2.png" alt="" class="img-responsive">
      </a>
    </div>

    <div class="row">
      <div class="col-sm-4">
        <div class="bot1_title">Jermaine Smith:</div>
        <p>
          9100 Olmsted Dr,<br>
Charlotte, NC.<br>
Telephone: 704-749-0528<br>
E-mail: <a href="#">tapssportsacademy@gmail.com</a>
        </p>
      </div>
      <div class="col-sm-4">
        <div class="bot1_title">Cynthia Smith:</div>
        <p>
          9100 Olmsted Dr,<br>
Charlotte, NC.<br>
Telephone:  704-749-0528<br>
E-mail: <a href="#">tapssportsacademy@gmail.com</a>
        </p>
      </div>
      <div class="col-sm-4">
        <div class="bot1_title">follow us:</div>
        <div class="social_wrapper">
          <ul class="social clearfix">
            
            <li><a href="#"><img src="/assets/social_ic3.png" alt=""></a></li>
            
          </ul>
        </div>
      </div>
    </div>
  </div>


</div>

<div class="bot2_wrapper">
  <div class="container">
    Copyright © 2016. All rights reserved.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  </div>
</div>

app/views/layouts/_header_taps.html.erb
<div class="top_wrapper">
  <div class="top_bg">
    <img src="/assets/sky2.jpg" alt="" class="sky2">
    <div class="grass1"></div>
    <div class="sun1"></div>
    <div class="green2"></div>
  </div>
  <div class="top_content">
    <div class="container">
      <header>
        <div class="logo_wrapper">
          <a href="index.html" class="logo">
            <img src="/assets/logo.png" alt="" class="img-responsive">
          </a>
        </div>
      </header>
      <%= render partial: '/layouts/tap_nav_header' %>

      <div class="snail1_wrapper">
        <div class="tree1 animated" data-animation="fadeIn" data-animation-delay="200"><img src="/assets/tree1.png" alt="" class="img-responsive"></div>
        <div class="snail1 animated" data-animation="bounceInLeft" data-animation-delay="300"><img src="/assets/snail1.png" alt="" class="img-responsive"></div>
      </div>
      <% if params[:action] == 'contact' %>
        <div class="page_title">Contact Us</div>
      <% elsif params[:query] == 'summer_camp' %>
         <div class="page_title">Summer Camp 2016</div>
      <% elsif params[:query] == 'queen_city' %>
         <div class="page_title">TAPS After School</div>
      <% elsif params[:query] == 'noresman_football' %>
         <div class="page_title">Norsemen Athletics</div>
      <%elsif params[:action] == 'about'%>
        <div class="page_title">little about us</div>
      <%else%>
      <%end%>

    </div>
  </div>
  <div class="wave1"></div>
</div>

app/views/layouts/_tap_nav_header.html.erb
<div class="menu_wrapper">
        <div class="navbar navbar_ navbar-default">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <div class="navbar-collapse navbar-collapse_ collapse">
            <ul class="nav navbar-nav sf-menu clearfix">
              <li class="nav1 active"><%=link_to 'Home', pages_path %></li>
              <li class="nav2"><%=link_to 'About',about_path %></li>
              <li class="nav3 sub-menu sub-menu-1"><%=link_to 'Programs',program_path %>
                <ul>
                  <!-- <li><%#=link_to 'Taps',tap_programs_path(query: "tap_after_sc")%></li></li> -->
                  <li><%=link_to 'TAPS After School',tap_programs_path(query: "taps_afterschool")%></li>
                  <li><%=link_to 'Summer Camp',tap_programs_path(query: "summer_camp")%></li>
                  <li><%=link_to 'Norsemen Athletics',tap_programs_path(query: "noresman_football")%></li>
                  <li><%=link_to 'School Closing Dates',tap_programs_path(query: "school_closing")%></li>
                  <li><%=link_to '10 Football Camp',football_camp_path%></li>
                  <li><%=link_to 'Gallery', gallery_path %></li>
                  <% if user_signed_in? %>
                    <li><%= link_to 'Profile', profiles_path %></li>
                  <%end%>
                </ul>
              </li>
              <% if user_signed_in? %>
                <li class="nav5"><%= link_to "Logout", destroy_user_session_path, :method => :delete %></li>
              <%else%>
                <li class="nav4"><%=link_to 'Sign Up', new_user_registration_path %></li>
                <li class="nav5"><%=link_to 'Log In', new_user_session_path %></li>
              <%end%>
              <li class="nav6"><%=link_to 'Contact us', contact_path%></li>
            </ul>
          </div>
        </div>
      </div>

app/views/layouts/new_layout.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <title>T.A.P.S</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <script src="//load.sumome.com/" data-sumo-site-id="ecf9e6a1561472401ffd7a3f8bbcd44adade533522cb0463d0f7cfa58d3a055b" async="async"></script>
  <%= javascript_include_tag "https://js.stripe.com/v1/", "application" %>
  <%= tag :meta, :name => "stripe-key", :content => STRIPE_PUBLIC_KEY %>
  <%#= javascript_include_tag 'gmaps.js' %>
  <%= csrf_meta_tags %>
</head>
<body>
	<% flash.each do |name, msg| %>
		<div class="alert alert-success fade in">
      <a href="#" class="close" data-dismiss="alert">&times;</a>
      <strong><%=msg%></strong>
    </div>
	<% end %>
  <%= yield %>
</body>
</html>

app/views/layouts/user_home_layout.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <title>T.A.P.S</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= javascript_include_tag "https://js.stripe.com/v1/", "application" %>
  <%= tag :meta, :name => "stripe-key", :content => STRIPE_PUBLIC_KEY %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%#=render partial: "layouts/nav_header" %>
  <%# flash.each do |name, msg| %>
    <%# if msg == "Thank you for your purchase!" || "Card details is invalid please check!" %> 
      <%#= content_tag :div, msg, class: "alert alert-info sucuess-msg" %>
    <%#end%>
  <%# end %>
  <%= yield %>
</body>
</html>